[[constraint]]
  name = "github.com/BurntSushi/toml"
  revision = "b26d9c308763d68093482582cea63d69be07a0f0"

[[constraint]]
  name = "github.com/andygrunwald/go-jira"
  revision = "9f1498acb69b5284c3953bfb90c529939c4dcb35"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.37"

[[constraint]]
  name = "github.com/bndr/gojenkins"
  revision = "fb64d609b014879a799204f02b50db404fc6d995"

[[constraint]]
  name = "github.com/bndr/gopencils"
  revision = "22e283ad76118c1e1f3812b4a3553809cd434e6a"

[[constraint]]
  name = "github.com/jszwedko/go-circleci"
  revision = "820efab65ef1993416cd18434ea18fe09b185627"

[[constraint]]
  name = "github.com/mcuadros/go-version"
  revision = "257f7b9a7d87427c8d7f89469a5958d57f8abd7c"

[[constraint]]
  name = "github.com/paetzke/godot"
  revision = "d6291c463cf5c9b21dab4a66e12d693c2bb9f202"

[[constraint]]
  name = "github.com/russross/blackfriday"
  revision = "5f33e7b7878355cd2b7e6b8eefc48a5472c69f70"

[[constraint]]
  name = "github.com/urfave/cli"
  revision = "88ae7af8d41d3842891a319ca21e867c490bcb0b"

[[constraint]]
  name = "golang.org/x/net"
  revision = "5bc3a08dc8042ac11f2752c257a2367c02ba32e8"

[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "d5040cddfc0da40b408c9a1da4728662435176a9"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  revision = "a14d7d367bc02b1f57d88de97926727f2d936387"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "a5b47d31c556af34a302ce5d659e6fea44d90de0"

[[constraint]]
  name = "github.com/manifoldco/promptui"
  version = "0.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision = "2aa2c176b9dab406a6970f6a55f513e8a8c8b18f"

[[constraint]]
  name = "github.com/google/go-github"
  revision = "fbfee053c26dab3772adfc7799d995eed379133e"

[[constraint]]
  name = "github.com/tmc/keyring"
  revision = "839169085ae146fc7a34bcb34dfd7ab216d23991"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.2.4"

[[constraint]]
  name = "github.com/mitchellh/go-wordwrap"
  revision = "ad45545899c7b13c020ea92b2072220eefad42b8"

[[constraint]]
  name = "github.com/hashicorp/vault"
  revision = "43493f27676a84db926dbb4c420f3b7d35bba13e"
